### ISSUE TITLE
Card lists can overflow into the footer in Deck View

### ISSUE THREAD

**Issue by emallson** [emallson/arenalander-league-bot#3]
![image](https://user-images.githubusercontent.com/4909458/80397962-f4107000-8884-11ea-9236-3db90b4a5ccc.png)

This only happens on decks with too many of a single card type (mostly creatures tbh). I found this CSS hack that pushes the footer down, but it might be better to automatically split it into `Creatures` and `Creatures - Continued`

```css
/* applied to the *parent* of div.deck-sections */
min-height: 1px;
overflow: hidden;
```

As part of this change, we should also move the `margin-bottom` for footer spacing from `div.deck-sections` to the footer or the parent.

**Comment by emallson** [comment]
Based on discussions with corporat, probably best to abandon flex entirely and use the `columns` css property (or `column-count` / `column-width`)

**Comment by anthonyronda** [comment]
As preached [here](https://medium.com/simple-human/stop-using-device-breakpoints-b11a87e2625c), I think it would make sense if our media query breakpoints were derived from minimum column width, rather than viewport size (we can still stretch to fit obviously)

pursuant to that, from line 65 to end of `base.css`

```
@media (min-width: 768px) {
    body {
        width: 60%;
        padding-left: 6.25%;
        /*padding-right: 6.25%;*/
    }

    div.title h1 {
        font-size: 3.2rem;
    }
    

    .fullsize-margin1 {
        margin-right: 1em;
    }

    .hidemobile {
        display: unset;
    }

    .mobile-scroll {
        overflow: initial;
    }
}
```
This is kind of clashing against my solution, since at 768px the content gets squished. Do we need this?

**Comment by emallson** [comment]
nope, there is nothing special about that breakpoint. it is copied from some old CSS i had lying around that I repurposed to get up and running quickly. if you've got a better solution for that, be my guest!

**Comment by anthonyronda** [comment]
There should probably be another pass on the CSS. Lots unused and we could probably stand to upgrade to using a pre-processor if/when another page gets added
